import {BadgePercent, Calculator, CreditCard, Plus, Trash2} from "lucide-react";
import {getPaymentAdminData} from "@/lib/data";
import {deleteRateAction, saveCardBrandAction, saveMachineAction, saveRateAction} from "./actions";

export const dynamic = "force-dynamic";

export default async function InstallmentAdminPage({searchParams}: {searchParams: Promise<{salvo?: string; erro?: string}>}) {
  const [data, params] = await Promise.all([getPaymentAdminData(), searchParams]);
  return <>
    <header className="admin-page-header"><div><p>Pagamentos</p><h1>Máquinas, bandeiras e taxas</h1><span>Cadastre a tabela real da máquina. O catálogo calcula produto e carrinho com a mesma regra.</span></div></header>
    {params.salvo && <div className="notice success">{decodeURIComponent(params.salvo)}</div>}
    {params.erro && <div className="notice error">{decodeURIComponent(params.erro)}</div>}
    <section className="payment-setup-grid">
      <form action={saveMachineAction} className="admin-panel form-section"><div className="admin-panel-heading"><span><Calculator /></span><div><p>Adquirente</p><h2>Adicionar máquina</h2></div></div><label>Nome interno<input name="name" required placeholder="PagBank, Stone, Ton..." /></label><label>Nome público<input name="publicName" placeholder="Opcional" /></label><div className="form-grid two"><label>Ordem<input name="sortOrder" type="number" min="0" defaultValue="0" /></label><label className="switch-label standalone"><input type="checkbox" name="passFee" defaultChecked /><span />Repassar taxa</label></div><button className="secondary-button" type="submit"><Plus />Salvar máquina</button></form>
      <form action={saveCardBrandAction} className="admin-panel form-section"><div className="admin-panel-heading"><span><CreditCard /></span><div><p>Cartão</p><h2>Adicionar bandeira</h2></div></div><label>Nome<input name="name" required placeholder="Visa, Mastercard, Elo..." /></label><label>URL da logo<input name="logoUrl" type="url" placeholder="https://..." /></label><label>Ordem<input name="sortOrder" type="number" min="0" defaultValue="0" /></label><button className="secondary-button" type="submit"><Plus />Salvar bandeira</button></form>
      <form action={saveRateAction} className="admin-panel form-section"><div className="admin-panel-heading"><span><BadgePercent /></span><div><p>Tabela</p><h2>Adicionar ou atualizar taxa</h2></div></div><div className="form-grid two"><label>Máquina<select name="machineId" required><option value="">Selecione</option>{data.machines.map((machine) => <option key={machine.id} value={machine.id}>{machine.name}</option>)}</select></label><label>Bandeira<select name="cardBrandId" required><option value="">Selecione</option>{data.cardBrands.map((brand) => <option key={brand.id} value={brand.id}>{brand.name}</option>)}</select></label><label>Parcelas<input name="installments" type="number" min="1" max="24" required /></label><label>Taxa percentual (%)<input name="percentRate" type="number" min="0" max="99.9999" step="0.0001" required /></label><label>Taxa fixa (R$)<input name="fixedFee" type="number" min="0" step="0.01" defaultValue="0" /></label><label>Valor mínimo (R$)<input name="minimumTotal" type="number" min="0" step="0.01" defaultValue="0" /></label></div><button className="primary-button" type="submit"><Plus />Salvar taxa</button></form>
    </section>

    <section className="admin-panel rates-panel"><div className="admin-panel-heading"><div><p>Condições cadastradas</p><h2>Tabela de parcelamento</h2></div><span>{data.rates.length} registros</span></div>{data.rates.length ? <div className="rates-table-wrap"><table className="rates-table"><thead><tr><th>Máquina</th><th>Bandeira</th><th>Parcelas</th><th>Taxa</th><th>Taxa fixa</th><th>Mínimo</th><th>Repasse</th><th /></tr></thead><tbody>{data.rates.map((rate) => <tr key={rate.id}><td>{rate.machineName}</td><td>{rate.cardBrandName}</td><td>{rate.installments}x</td><td>{rate.percentRate.toFixed(4)}%</td><td>R$ {rate.fixedFee.toFixed(2)}</td><td>R$ {rate.minimumTotal.toFixed(2)}</td><td>{rate.passFeeToCustomer ? "Cliente" : "Loja"}</td><td><form action={deleteRateAction}><input type="hidden" name="id" value={rate.id} /><button className="danger-icon" type="submit" aria-label="Remover taxa"><Trash2 /></button></form></td></tr>)}</tbody></table></div> : <div className="empty-admin-state">Cadastre ao menos uma máquina, uma bandeira e uma taxa.</div>}</section>
  </>;
}
