import type {CatalogSettings, PublicProduct} from "@/lib/types";

export const demoSettings: CatalogSettings = {
  catalogName: "Origem",
  logoUrl: "",
  whatsapp: "",
  whatsappMessageTemplate: "Olá! Quero atendimento sobre os produtos abaixo:",
  instagram: "",
  address: "Brasília - DF",
  mapsUrl: "",
  businessHours: "Segunda a sábado",
  footerText: "Tecnologia com procedência, preço e atendimento direto.",
  maxInstallments: 12,
  defaultMachineId: null,
  defaultCardBrandId: null,
};

export const demoProducts: PublicProduct[] = [
  {
    id: 1,
    externalId: "demo-attack-shark-x11",
    slug: "mouse-gamer-attack-shark-x11",
    name: "Mouse Gamer Attack Shark X11 Tri-Mode com Dock RGB",
    sku: "ATTACK SHARK X11 - BLACK",
    ean: "",
    shortDescription: "Mouse gamer sem fio com três modos de conexão e base de carregamento RGB.",
    descriptionHtml: "<p>Desempenho, autonomia e uma base que não passa despercebida.</p>",
    brand: "Attack Shark",
    brandSlug: "attack-shark",
    brandLogoUrl: "",
    category: "Mouses",
    categorySlug: "mouses",
    images: ["https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80"],
    attributes: {Conexão: "2.4 GHz, Bluetooth e USB-C", Cor: "Preto"},
    stockStatus: "available",
    featured: true,
    salePrice: 299.99,
    promotionalPrice: 279.99,
    effectivePrice: 279.99,
    promotionActive: true,
  },
  {
    id: 2,
    externalId: "demo-ajazz-r82he",
    slug: "teclado-magnetico-ajazz-r82he",
    name: "Teclado Magnético Ajazz R82HE Hall Effect",
    sku: "AJAZZ R82HE",
    ean: "",
    shortDescription: "Teclado gamer Hall Effect com resposta rápida e ajustes avançados.",
    descriptionHtml: "<p>Precisão magnética para jogos competitivos e uso diário.</p>",
    brand: "Ajazz",
    brandSlug: "ajazz",
    brandLogoUrl: "",
    category: "Teclados",
    categorySlug: "teclados",
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80"],
    attributes: {Tecnologia: "Hall Effect", Layout: "Compacto"},
    stockStatus: "available",
    featured: true,
    salePrice: 599.99,
    promotionalPrice: null,
    effectivePrice: 599.99,
    promotionActive: false,
  },
  {
    id: 3,
    externalId: "demo-arzopa-z1fc",
    slug: "monitor-portatil-arzopa-z1fc",
    name: "Monitor Portátil Arzopa Z1FC 16,1 polegadas 144 Hz",
    sku: "ARZOPA Z1FC",
    ean: "",
    shortDescription: "Tela portátil Full HD com alta taxa de atualização.",
    descriptionHtml: "<p>Mais espaço para trabalhar e jogar onde estiver.</p>",
    brand: "Arzopa",
    brandSlug: "arzopa",
    brandLogoUrl: "",
    category: "Monitores Portáteis",
    categorySlug: "monitores-portateis",
    images: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80"],
    attributes: {Tela: "16,1 polegadas", Frequência: "144 Hz"},
    stockStatus: "available",
    featured: false,
    salePrice: 620,
    promotionalPrice: null,
    effectivePrice: 620,
    promotionActive: false,
  },
];
